# Generated by Django 6.0.3 on 2026-04-04 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('dominio', models.CharField(choices=[('ORGANIZACIONAL', 'Organizacional'), ('PERSONAS', 'Personas'), ('FISICO', 'Físico'), ('TECNOLOGICO', 'Tecnológico')], max_length=20)),
                ('descripcion_guia', models.TextField()),
            ],
            options={
                'verbose_name': 'Control ISO',
                'verbose_name_plural': 'Controles ISO',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PEQUENA', 'Pequeña'), ('MEDIANA', 'Mediana')], max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('IMPLEMENTADO', 'Implementado'), ('NO_IMPLEMENTADO', 'No Implementado'), ('NO_APLICA', 'No Aplica')], default='NO_IMPLEMENTADO', max_length=20)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='implementacion.controliso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='implementacion.empresa')),
            ],
            options={
                'verbose_name': 'Evaluación de Control',
                'verbose_name_plural': 'Evaluaciones de Controles',
                'unique_together': {('empresa', 'control')},
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='implementacion.evaluacioncontrol')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
