# Generated by Django 6.0.3 on 2026-04-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementacion', '0003_alter_empresa_nombre_alter_evaluacioncontrol_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_solicitud_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solicitud de Revisión'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='revision_solicitada',
            field=models.BooleanField(default=False, help_text='Indica si la implementación se envió a auditoría y está pendiente de atención.', verbose_name='Revisión Solicitada'),
        ),
    ]
