# Generated by Django 6.0.3 on 2026-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementacion', '0004_empresa_fecha_solicitud_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacioncontrol',
            name='estado',
            field=models.CharField(choices=[('IMPLEMENTADO', 'Implementado'), ('EN_PROCESO', 'En Proceso'), ('NO_IMPLEMENTADO', 'No Implementado'), ('NO_APLICA', 'No Aplica')], default='NO_IMPLEMENTADO', max_length=20),
        ),
    ]
