# Generated by Django 6.0.3 on 2026-04-06 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implementacion', '0004_empresa_fecha_solicitud_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_por_admin', models.BooleanField(default=False, help_text='True cuando el curso es oficial y global de Aegis.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_creados_capacitacion', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_capacitacion', to='implementacion.empresa')),
            ],
            options={
                'verbose_name': 'Curso de Capacitacion',
                'verbose_name_plural': 'Cursos de Capacitacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ModuloContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF / Lectura'), ('CUESTIONARIO', 'Cuestionario')], max_length=20)),
                ('url_recurso', models.URLField(max_length=700)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('duracion_minutos', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='capacitacion.cursocapacitacion')),
            ],
            options={
                'verbose_name': 'Modulo de Contenido',
                'verbose_name_plural': 'Modulos de Contenido',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_completado', models.PositiveIntegerField(default=0)),
                ('curso_completado', models.BooleanField(default=False)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='capacitacion.cursocapacitacion')),
                ('modulos_completados', models.ManyToManyField(blank=True, related_name='progresos_usuarios', to='capacitacion.modulocontenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_capacitacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
                'ordering': ['-fecha_ultima_actividad'],
            },
        ),
        migrations.AddConstraint(
            model_name='cursocapacitacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('creado_por_admin', True), ('empresa__isnull', True)), models.Q(('creado_por_admin', False), ('empresa__isnull', False)), _connector='OR'), name='curso_capacitacion_visibilidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='modulocontenido',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='modulo_orden_unico_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='progresousuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='progreso_unico_usuario_curso'),
        ),
    ]
