# Generated by Django 6.0.3 on 2026-04-05 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementacion', '0003_alter_empresa_nombre_alter_evaluacioncontrol_empresa'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='implementacion.empresa', verbose_name='Empresa'),
        ),
    ]
