# Generated by Django 6.0.3 on 2026-04-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariocustom_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='es_administrador_empresa',
            field=models.BooleanField(default=False, help_text='Indica si el usuario administra su equipo dentro de la empresa.', verbose_name='Administrador de Empresa'),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indica si el usuario fue aprobado por el administrador de su empresa.', verbose_name='Aprobado'),
        ),
    ]
