# Generated by Django 6.0.3 on 2026-04-06 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementacion', '0003_alter_empresa_nombre_alter_evaluacioncontrol_empresa'),
        ('usuarios', '0003_usuariocustom_es_administrador_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSeguridadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION_USUARIO', 'Creación de Usuario'), ('ACTUALIZACION_USUARIO', 'Actualización de Usuario'), ('CAMBIO_ROL', 'Cambio de Rol'), ('INACTIVACION_USUARIO', 'Inactivación de Usuario'), ('RESET_PASSWORD_FORZADO', 'Reseteo Forzado de Contraseña'), ('APROBACION_USUARIO', 'Aprobación de Usuario'), ('RECHAZO_USUARIO', 'Rechazo de Usuario')], max_length=40, verbose_name='Acción')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='Detalle Técnico')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_bitacora_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora_usuarios', to='implementacion.empresa', verbose_name='Empresa Relacionada')),
                ('usuario_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Objetivo')),
            ],
            options={
                'verbose_name': 'Bitácora de Seguridad de Usuario',
                'verbose_name_plural': 'Bitácoras de Seguridad de Usuarios',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['accion', 'fecha_evento'], name='usuarios_bi_accion_5551af_idx'), models.Index(fields=['empresa', 'fecha_evento'], name='usuarios_bi_empresa_eba4e9_idx'), models.Index(fields=['actor', 'fecha_evento'], name='usuarios_bi_actor_i_322dea_idx')],
            },
        ),
    ]
