# Generated by Django 6.0.3 on 2026-04-06 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_bitacoraseguridadusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraseguridadusuario',
            name='accion',
            field=models.CharField(choices=[('CREACION_USUARIO', 'Creación de Usuario'), ('ACTUALIZACION_USUARIO', 'Actualización de Usuario'), ('CAMBIO_ROL', 'Cambio de Rol'), ('INACTIVACION_USUARIO', 'Inactivación de Usuario'), ('RESET_PASSWORD_FORZADO', 'Reseteo Forzado de Contraseña'), ('APROBACION_USUARIO', 'Aprobación de Usuario'), ('RECHAZO_USUARIO', 'Rechazo de Usuario'), ('LOGIN_EXITOSO', 'Login Exitoso'), ('LOGIN_FALLIDO', 'Login Fallido'), ('LOGOUT', 'Cierre de Sesión')], max_length=40, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='bitacoraseguridadusuario',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
    ]
