# Generated by Django 6.0.3 on 2026-04-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='rol',
            field=models.CharField(choices=[('EMPLEADO', 'Empleado'), ('IMPLEMENTADOR', 'Implementador'), ('AUDITOR', 'Auditor'), ('LIDER_EQUIPO', 'Líder de Equipo'), ('CAPACITADOR', 'Capacitador')], default='EMPLEADO', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
    ]
