# Generated by Django 6.0.3 on 2026-04-04 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implementacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veredicto', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme'), ('NO_APLICA', 'No Aplica')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='implementacion.evaluacioncontrol')),
            ],
            options={
                'verbose_name': 'Revisión de Auditoría',
                'verbose_name_plural': 'Revisiones de Auditorías',
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
