# Generated by Django 6.0.3 on 2026-04-04 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('implementacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionauditoria',
            name='evaluacion_control',
            field=models.ForeignKey(default=1, help_text='Control ISO que está siendo auditado', on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_auditoria', to='implementacion.evaluacioncontrol', verbose_name='Evaluación del Control'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisionauditoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='fecha_revision',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Hallazgos, recomendaciones o comentarios', null=True, verbose_name='Observaciones del Auditor'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='veredicto',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme'), ('NO_APLICA', 'No Aplica')], max_length=20, verbose_name='Veredicto de Auditoría'),
        ),
        migrations.CreateModel(
            name='ProcesoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Auditoría Anual 2026, Auditoría de Recertificación Q1', max_length=200, verbose_name='Nombre del Proceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha en que el proceso fue finalizado', null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20, verbose_name='Estado del Proceso')),
                ('auditor', models.ForeignKey(help_text='Usuario con rol AUDITOR_INTERNO asignado al proceso', on_delete=django.db.models.deletion.CASCADE, related_name='procesos_auditoria_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Responsable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_auditoria', to='implementacion.empresa', verbose_name='Empresa Auditada')),
            ],
            options={
                'verbose_name': 'Proceso de Auditoría',
                'verbose_name_plural': 'Procesos de Auditoría',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='revisionauditoria',
            name='proceso',
            field=models.ForeignKey(default=1, help_text='Programa de auditoría al que pertenece esta revisión', on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='auditoria.procesoauditoria', verbose_name='Proceso de Auditoría'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='revisionauditoria',
            unique_together={('proceso', 'evaluacion_control')},
        ),
        migrations.AddIndex(
            model_name='revisionauditoria',
            index=models.Index(fields=['proceso', 'veredicto'], name='auditoria_r_proceso_e2b7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionauditoria',
            index=models.Index(fields=['auditor', 'fecha_revision'], name='auditoria_r_auditor_f1ac8f_idx'),
        ),
        migrations.AddIndex(
            model_name='procesoauditoria',
            index=models.Index(fields=['empresa', 'estado'], name='auditoria_p_empresa_64eb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='procesoauditoria',
            index=models.Index(fields=['auditor', 'estado'], name='auditoria_p_auditor_59c4d0_idx'),
        ),
        migrations.RemoveField(
            model_name='revisionauditoria',
            name='evaluacion',
        ),
    ]
