# Generated by Django 6.0.3 on 2026-04-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_revisionauditoria_evaluacion_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionauditoria',
            name='estado_implementacion_snapshot',
            field=models.CharField(blank=True, choices=[('IMPLEMENTADO', 'Implementado'), ('NO_IMPLEMENTADO', 'No Implementado'), ('NO_APLICA', 'No Aplica')], help_text='Copia del estado del control al momento de la auditoría', max_length=20, null=True, verbose_name='Estado de Implementación (Snapshot)'),
        ),
        migrations.AddField(
            model_name='revisionauditoria',
            name='justificacion_snapshot',
            field=models.TextField(blank=True, help_text='Copia de la justificación al momento de la auditoría', null=True, verbose_name='Justificación (Snapshot)'),
        ),
    ]
