# Generated by Django 6.0.3 on 2026-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_revisionauditoria_estado_implementacion_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoauditoria',
            name='visible_para_auditor',
            field=models.BooleanField(default=True, help_text='Permite ocultar el proceso del panel del auditor sin eliminar registros.', verbose_name='Visible para Auditor'),
        ),
    ]
