# Generated by Django 6.0.3 on 2026-04-05 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_procesoauditoria_visible_para_auditor'),
        ('implementacion', '0002_evaluacioncontrol_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionauditoria',
            name='evaluacion_control',
            field=models.ForeignKey(help_text='Control ISO que está siendo auditado', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_auditoria', to='implementacion.evaluacioncontrol', verbose_name='Evaluación del Control'),
        ),
    ]
