# Generated by Django 6.0.3 on 2026-04-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_alter_revisionauditoria_evaluacion_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionauditoria',
            name='estado_snapshot',
            field=models.CharField(blank=True, help_text='Estado del control guardado como instantánea histórica.', max_length=20, null=True, verbose_name='Estado Snapshot'),
        ),
    ]
