# Generated by Django 6.0.3 on 2026-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_add_evidencias_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionauditoria',
            name='estado_implementacion_snapshot',
            field=models.CharField(blank=True, help_text='Estado de implementación de los controles congelado(s) al momento de registrar esta revisión individual.', max_length=20, null=True, verbose_name='Estado de Implementación (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='evidencias_snapshot',
            field=models.JSONField(blank=True, help_text='Evidencia(s) de los controles congelada(s) al momento de registrar esta revisión individual. Formato: [{"id": 1, "archivo": "/media/evidencias/file.pdf", "fecha_subida": "2026-04-05"}]', null=True, verbose_name='Evidencias (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='justificacion_snapshot',
            field=models.TextField(blank=True, help_text='Justificación de los controles congelada(s) al momento de registrar esta revisión individual.', null=True, verbose_name='Justificación (Snapshot)'),
        ),
    ]
