# Generated by Django 6.0.3 on 2026-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0009_alter_revisionauditoria_estado_implementacion_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionauditoria',
            name='implementador_snapshot',
            field=models.CharField(blank=True, help_text='Nombre del responsable de la implementación al momento de registrar la revisión individual.', max_length=200, null=True, verbose_name='Implementador (Snapshot)'),
        ),
    ]
