# Generated by Django 6.0.3 on 2026-04-05 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0010_revisionauditoria_implementador_snapshot'),
        ('implementacion', '0003_alter_empresa_nombre_alter_evaluacioncontrol_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoauditoria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_auditoria', to='implementacion.empresa', verbose_name='Empresa Auditada'),
        ),
    ]
