# Generated by Django 6.0.3 on 2026-04-06 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0011_alter_procesoauditoria_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoauditoria',
            name='auditor',
            field=models.ForeignKey(help_text='Usuario con rol AUDITOR asignado al proceso', on_delete=django.db.models.deletion.CASCADE, related_name='procesos_auditoria_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Responsable'),
        ),
    ]
