# Generated by Django 6.0.3 on 2026-04-06 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0012_alter_procesoauditoria_auditor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoauditoria',
            name='auditor',
            field=models.ForeignKey(blank=True, help_text='Usuario con rol AUDITOR asignado al proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_auditoria_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Responsable'),
        ),
        migrations.AlterField(
            model_name='revisionauditoria',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
    ]
